### ISSUE TITLE
"Affine transform" not working

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#114]
**Describe the bug**
"Affine transform" not working

**To Reproduce**
1. Go to _Custom settings >  Sketching_ and enable both _Sketch shift/scale_ and _Affine transform_ options.
2. Open a sketch
3. Enable _Fix refs_ in the _Sketch References_ dialog. 
4. See that, no matter if you use two or three fingers, the only available transformation is scaling. Rotation and skewing is not possible.

**Expected behavior**
When using three fingers both rotation and skewing should also be possible as mentioned in man page page_shift.htm

**Device:**
 - Galaxy Samsung 23 FE
 - Android 14
 - TopoDroid 6.2.64

**Comment by marcocorvi** [comment]
threePointers must survive method call.
as a matter of fact it is not a necessary variable.
it is fixed and it will be in the next commit.
