### ISSUE TITLE
Colored splays not shown with proper color in shot list

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#115]
**Describe the bug**
Colored splays not shown with proper color in shot list

**To Reproduce**
1. Color some splays either in shot edit dialog or in multisselection
2. Click on the "refresh" button or go back and forf to sketch window
3. See that the colored splay is not shown colored in the shot list. It is properly colored in the sketch window.

**Expected behavior**
Colored splay should appear colored in the shot list.

**Device:**
 - Galaxy Samsung 23 FE
 - Android 14
 - TopoDroid 6.2.65

**Comment by marcocorvi** [comment]
fixed in 6.2.67
