### ISSUE TITLE
'address' column empty in 'qSurveysStat1' inside 'getSurveyStat' from 'DataHelper'

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#117]
**Describe the bug**
'address' column empty in 'qSurveysStat1' inside 'getSurveyStat' from 'DataHelper'

**To Reproduce**
1. Go to 'Survey info'
2. Click on the 'Info' button
3. See that the 'Devices' data count is empty

**Expected behavior**
To see the actual data count for each used device in the survey.

**Device:**
 - Samsung Galaxy 23 FE
 - Android 14
 - TopoDroid 6.2.65

**Comment by marcocorvi** [comment]
not reproduced
