### ISSUE TITLE
Help button on "Projected profile azimuth" dialog does not work

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#119]
**Describe the bug**
Help button on "Projected profile azimuth" dialog does not work

**To Reproduce**
1. Go to new sketch
2. Click on "projected profile" checkbox
3. Click on "Ok"
4. Click on "?"
5. See that the help page is not presented

**Expected behavior**
For the "page_projection.htm" help page to be presented

**Device:**
 - Samsung Galaxy 23FE
 - Android 14
 - TopoDroid 6.2.72

**Comment by rsevero** [comment]
Fixed with commit 29f44d322

**Comment by marcocorvi** [comment]
why not initLayout ?

**Comment by rsevero** [comment]
> why not initLayout ?

I tried it but the layout of the dialog box changed: the title disappeared and the dialog box got larger.

And it was not used before, just "setContentView".

Appart from that, yes, "initLayout" would be better, for sure.

**Comment by marcocorvi** [comment]
that is probably a problem of the layout file

**Comment by rsevero** [comment]
> that is probably a problem of the layout file

Can you try to fix the layout so "initLayout" would work?

I don't know anything about layouts in java. It's the "ProjectionDialog" layout.

**Comment by marcocorvi** [comment]
fixed.
please revert your changes.

**Comment by rsevero** [comment]
Done
