### ISSUE TITLE
Create a "delete scrap" button

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#121]
**Is your feature request related to a problem? Please describe.**
There is not way to delete a extra scrap created n a sketch.

**Describe the solution you'd like**
The "Scraps" dialog box openned when clicking on the menu option "scrap" in the Drawing window could include a delete option.

**Comment by marcocorvi** [comment]
indeed scrap delete could be done, as long as there are more than one scrap.

there might be issues with the scrap index.

which scrap becomes active when the current scrap is deleted ?
