### ISSUE TITLE
Make "too long shots" available with other deleted shots

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#122]
**Is your feature request related to a problem? Please describe.**
When a shot is discarded by Topodroid because it's too long according to "max shot length" setting, instead of being simply discarded and getting lost for the user, it should be available at the "restore/undelete" buffer so the user can use a longer than expected shot without having to change the "max shot length" **and** redoing the shot.

**Comment by marcocorvi** [comment]
so it should already be
