### ISSUE TITLE
Missing xml/button_l and iz_swap

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#126]
**Describe the bug**
Missing xml/button_l and iz_swap

**To Reproduce**
1. Try to compile current code
2. See error "missing xml/button_l" and "missing iz_swap"

**Expected behavior**
Current code compile cleanly

**Comment by marcocorvi** [comment]
added under git.
will be in the next push.

**Comment by marcocorvi** [comment]
fixed in the next push
