### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by marcocorvi** [marcocorvi/topodroid#13]
Ukraninian translation need fix before it can be included in the apk:

compiler issue: apostrophe must be escaped

lint issues: several (run lint to see them all. hopefully they do not crash the app).
N.B. some lint warnings can be ignored. For example
*Value array strings need not be translated  
page_* strings must not be translated

Consistency issue: need the work ukrainian in ukrainian in default array.xml

**Comment by finchatticus** [comment]
#14
