### ISSUE TITLE
item groups in svg export  for round-trip

### ISSUE THREAD

**Issue by marcocorvi** [marcocorvi/topodroid#132]
**Describe the bug**
the option for item groups does not work for the svg export for walls round-trip

**Expected behavior**
svg file has items grouped by the therion type.

**Comment by marcocorvi** [comment]
completed with pull request n.53 "SVG layers for SvgWalls and XSections"
by R. Severo

**Comment by rsevero** [comment]
There were a bug in non-grouped SvgWalls export in my code you merged yesterday.

I already commited the fix but it might be a good idea to make release 6.3.11 soon.

Sorry for the trouble.

**Comment by marcocorvi** [comment]
i wait some time, in case other bugs come up.
