### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by finchatticus** [marcocorvi/topodroid#15]
i'm got some errors in TopoDroidPreferences.java

Error:(96, 41) java: cannot find symbol
  symbol:   variable prefs_4_calib
  location: class com.topodroid.DistoX.R.xml

Error:(102, 41) java: cannot find symbol
  symbol:   variable prefs_4
  location: class com.topodroid.DistoX.R.xml

**Comment by marcocorvi** [comment]
Maybe these two files are not yet under git
