### ISSUE TITLE
ukrainian and other translations

### ISSUE THREAD

**Issue by marcocorvi** [marcocorvi/topodroid#16]
This is an "abriged" output of lint.

Please review the translation warnings that refer to the language you are maintaining.

lint is far from perfect,
therefore some warning do not need to be taken into account
( should make an exception file, but i'm lazy/busy ).
ignore those.

**Comment by Tapter** [comment]
Could you attach the output; or where do i see that?

**Comment by marcocorvi** [comment]
oops.
here is the link

[lint.txt](https://github.com/marcocorvi/topodroid/files/281496/lint.txt)

**Comment by marcocorvi** [comment]
dropped old lint outputs from int18
and added a new one.
@all please check (possible) issues with your translation
thanks

**Comment by marcocorvi** [comment]
hungarian translation

i noticed that hungarian translation contains english strings as well as the translations.
it is likely that this makes the strings too long so that, at times, they exceed the widgets space,
with the result that the translated string is cut at the first few chars.

what is the motivation for this choice ?
would not be better to keep only the translation ?

**Comment by Szifon** [comment]
Sorry for any disturbances. I have no routine in the use of GIT and in
coding. I keep the English string temporary because I would like to recheck
the translation when I have finished it. I will delete them.

Péter Sűrű

**Comment by marcocorvi** [comment]
that's ok

i was just wondering why the double strings.
i appreciate your help, and that of all others, for the translations,
And the comments to make the app better.

marco

**Comment by fato63** [comment]
Ciao Marco,
I have just updated the IT String.xml file.
I have found, about at line 883, a group of lines in English without "TODO".
Is it correct?

Fabrizio

2016-10-11 13:29 GMT+02:00 marco corvi <notifications@github.com>:

> that's ok
>
> i was just wondering why the double strings.
> i appreciate your help, and that of all others, for the translations,
> And the comments to make the app better.
>
> marco
>

**Comment by marcocorvi** [comment]
Sorry, i must have missed the TODOs

if a string has an english value it is a TODO.

marco
