### ISSUE TITLE
SVG output is outside of viewing Box 

### ISSUE THREAD

**Issue by caveradam** [marcocorvi/topodroid#21]
Using Version 3.1.6i. 

The SVG output goes outside of the bounding box. This only affects simple viewers. Major editors such as Inkscape or Illustrator will handle this fine. 

Priority: Low.

![svg point output](https://cloud.githubusercontent.com/assets/12676475/19629491/6c127e06-9944-11e6-9e97-c215bb2a6334.png)

**Comment by marcocorvi** [comment]
svg export does not have a global translation, therefore coords can be negative.
if i remember well svg origin is at the upper-left corner.

it would not be hard to shift the svg output as the sketch bounding box is already computed.

**Comment by marcocorvi** [comment]
added overall shift to svg export
