### ISSUE TITLE
Portuguese "Português" is not presented as a language option

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#64]
Portuguese "Português" is not presented as a language option at the "Language" (App language) setting list.

If my cel phone is in portuguese and I choose the "default" option I get Topodroid in portuguese but I can't drectly choose "Portuguese" as there is no such option in the language setting list.

Tested in version 6.1.97-33

**Comment by marcocorvi** [comment]
thanks

**Comment by marcocorvi** [comment]
fixed
