### ISSUE TITLE
Wrong Therion line type export

### ISSUE THREAD

**Issue by RaymondMichael** [marcocorvi/topodroid#66]
When you export a TopoDroid sketch to a Therion .th2, the line types for ceiling & floor ledges are wrong. A TopoDroid ceiling ledge is export as a "chimney", and floor ledge is exported as a "pit".

**Comment by marcocorvi** [comment]
topodroid exports symbols to therion using the "therion name" written in the symbol file, which must coincide with the symbol filename.
there is no line symbol named ceiling-ledge nor floor-ledge.

**Comment by RaymondMichael** [comment]
In Therion it's ceiling-step and floor-step.

**Comment by marcocorvi** [comment]
there are ceiling-step and floor-step in a set of additional symbols
