### ISSUE TITLE
Bug? - Line connection button missing from sketch page

### ISSUE THREAD

**Issue by Greenman126** [marcocorvi/topodroid#68]
The line continuation button which usually allows you choose between [-none -start point -end point -both points -continue] seems to be missing. I have asked others and we cannot find it. We checked basic, normal, expert and tester mode.

![Screenshot_20230314-172837_TopoDroid-X](https://user-images.githubusercontent.com/112777889/225156547-e5e3dbe9-2f31-44a6-a4ca-c6013a48a6b5.jpg)

**Comment by Greenman126** [comment]
Button missing on both a Samsung Active Tab 2 and Samsung Galaxy s20 FE

**Comment by marcocorvi** [comment]
continuation has been replaced by retracing

**Comment by Greenman126** [comment]
Thank you. I figured out I could activate this by long-pressing the line/area/point select button
