### ISSUE TITLE
Hide from not working as expected: unlink shots still being shown

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#69]
When I hide shots from a certain station I expected that all shots/stations "behind" it (by behind I mean, that where linked to the survey only through the hidden shot) are removed from the sketch but this is failing on the provided survey: https://we.tl/t-3uaBBEfbHO 

**To Reproduce**
1. Import the provided "Pratinha-4L" survey
2. Open the second plan sketch
3. At shot 4L21/4L22 hide shots from 4L21
4. See how we have many more shots sown than only the ones that are actually directly connected to the drawn sketch
5.  
**Expected behavior**
I expected that all other shots, disconnected by 4L21 were hdden (like 4l19, 4L49, 4L6 and so on)

**Screenshots**
![Screenshot_20230318-070425_TopoDroid-X](https://user-images.githubusercontent.com/315152/226099004-913a8478-8e81-444b-bcad-0fc81db0e221.jpg)

**Device (please complete the following information):**
 - Samsung Note8
 - Android version: 9
 - TopoDroid version: 6.1.97-33

**Comment by marcocorvi** [comment]
this is a long standing problem.
see comment in tdnum line 415.

**Comment by marcocorvi** [comment]
probably fixed 6.2.1 next
