### ISSUE TITLE
x-section SVG export does not include grid when selected

### ISSUE THREAD

**Issue by lostgravity** [marcocorvi/topodroid#70]
**Describe the bug**
When exporting cross sections and selecting the box to include the grid, the grid does not show up in the export.

**To Reproduce**
1. In profile or plan view (in my case), select and open (or create new) x-section between two points
2. Click on `Export`
3. Select SVG; select `Grid` and deselect all other options
4. Save

**Expected behavior**
The SVG includes the grid, just like it does for profile and plan export into SVG.

**Screenshots**

**Device (please complete the following information):**
 - Make and model: Samsung SM-T397U
 - Android version: 9
 - TopoDroid version: 6.2.0-33

**Additional context**

**Comment by marcocorvi** [comment]
probably fixed 6.2.1 next
