### ISSUE TITLE
Line style bezier is ignored when continuing a line 

### ISSUE THREAD

**Issue by mark-dickey** [marcocorvi/topodroid#71]
Issue:  If you have a line drawn as style bezier, and continue/retrace this line (with your line style still set to bezier) it will continue as "normal" instead.

Confirmed in the newest release but existed in 5.1, 6.0, 6.1 and now 6.2.  Finally opening a bug report. :)

Duplicate:

1. Set your "Line style" to "Bezier"
2. Draw a line
3. Long press the drawing tool selection icon such that you are in "continuing" or "retracing" mode
4. Extend the original line
5. Go into editing mode
6. Review the number of control points of the line -- the first portion will be "bezier" the second portion will be "normal"

https://user-images.githubusercontent.com/119517516/226335297-8666647c-03fa-4730-ab92-f7877fea2468.mp4

**Comment by mark-dickey** [comment]
Interesting. Is this behavior planned?  I would have expected the transformations to be applied to the newly traced linepoints after which the new linepoints are joined into the existing line.

That way the number of linepoints/type of line is consistent across the retraced/entire line?

For example, if I take this retraced line and try to reduce the number of linepoints (decimation) it will do so equally across the entire line. This will cause issues as the first portion is bezier with few points, and the second portion will have many points.

If this is not a bug, is it a functionality change that would be desired? When retracing a line, the line style of the original line dictates how the retraced line is created so as to maintain consistency?

(I can do a video of the decimation example if there is any interest.)

**Comment by mark-dickey** [comment]
Also, I am not asking for you to do extra work.  If this is desired functionality, I can look at the code and see if I can provide a commit eventually. I appreciate how much work TopoDroid is, and what you've done is awesome.

**Comment by marcocorvi** [comment]
you may create a new class DrawingPointLineFilter with a static method
transform() which takes an input pointline (the traced line, possibly
shortened), an output pointline (to fill with linepoints) and apply the
proper transform, according to the current linestyle.

this will remove a piece of work from drawingwindow, and avoid some code
replication.

**Comment by mark-dickey** [comment]
Thanks for the guidance!  It might be a while, but I'll be looking at it. Survey course I'm taking/helping at starts tomorrow here in Israel, then an expedition next month in Mexico. Thanks for your time!

**Comment by marcocorvi** [comment]
for the time being i add a notice to the manual.

when can the users expect that the bug may be fixed ?

**Comment by marcocorvi** [comment]
any progress ?

the bug ought to be fixed

**Comment by marcocorvi** [comment]
Mark Dickey made no work.
