### ISSUE TITLE
Alternate palettes not appearing in Drawing Tools Selector

### ISSUE THREAD

**Issue by Greenman126** [marcocorvi/topodroid#73]
**Describe the bug**

**To Reproduce**
1. Go to '...' in the Top right of the starting page
2. Click on 'PALETTE'
3. No checkboxes or alternate tool symbols visible

**Screenshots**
![image](https://github.com/marcocorvi/topodroid/assets/112777889/42ea2d7a-7679-4cbc-aaef-c0c8cbc70d3b)

**Device (please complete the following information):**
 - Samsung Active Tab2
 - Android 9.0
 - TopoDroid version 6.2.9-33

**Additional context**
This has happened in other versions and I'm not sure if it's a version issue or it just sometimes doesn't work for an odd reason.

**Comment by rsevero** [comment]
Do you have the "Custom settings >> Palettes" option enabled?

**Comment by Greenman126** [comment]
Yes, that is exactly the problem! I made the mistake of only turning on "Expert" mode when I should have turn on "Tester"

I recommend we move the alternate palettes option out of "Tester" and into "Normal". Seems like too important of a feature to hide.
