### ISSUE TITLE
Retracing issue when drawing lines

### ISSUE THREAD

**Issue by Greenman126** [marcocorvi/topodroid#74]
When drawing lines with retracing enabled, you cannot connect the end of a new line to the start of an old line. Attempting to do this, without retracing the entire wall, results in the older line being overwritten/destroyed.

Unless I am mistaken, this makes it impossible to connect lines to the origin point of old lines. This forces the user to retrace the entire old line every time they draw a new segment of the wall.

Is there a way around this? Is there a way to re-enable the old Line Connection functions?

EDIT: Alternately, if anyone has a link to an APK from before the retrace feature was added, I would appreciate it. 
EDIT2: I found an old APK download, so I am reverting to that for now.

**Comment by marcocorvi** [comment]
retracing has been taken up by Mark Dickey - see issue #71
i am still waiting feedback from him.

**Comment by marcocorvi** [comment]
On Fri, May 12, 2023 at 11:36 PM Greenman126 ***@***.***>
wrote:

> When drawing lines with retracing enabled, you cannot connect the end of a
> new line to the start of an old line. Attempting to do this, without
> retracing the entire wall, results in the older line being
> overwritten/destroyed.
>
> Unless I am mistaken, this makes it impossible to connect lines to the
> origin point of old lines. This forces the user to retrace the entire old
> line every time they draw a new segment of the wall.
>
> Is there a way around this?
>
retracing has been taken up by Mark Dickey,
see issue #71 on github.

> Is there a way to re-enable the old Line Connection functions?
>
no.
the code is no longer in the sources.

marco

**Comment by marcocorvi** [comment]
the reported behavior could not be reproduced.

**Comment by Greenman126** [comment]
Marco, I just tried this again (on a separate device too) and found that it only happens with bezier curves line type.

**Comment by marcocorvi** [comment]
indeed that was what mark dickey had pledged to work on.

**Comment by marcocorvi** [comment]
maybe i add a note in the manual that retracing does not work with bezier
and disable it for bezier lines

**Comment by Greenman126** [comment]
Great. Thank you for being so responsive and for all your hard work Marco!

**Comment by Greenman126** [comment]
Another suggestion: Give retracing its own toggle button.

I teach a lot of people about topodroid and I have difficulty explaining
how to enable and disable it. The long-press on the drawing tool button is
not very intuitive.

**Comment by marcocorvi** [comment]
i considered that, but
(1) it is a frequent action thus it needs a button
(2) the number of buttons must be kept to a minimum.
