### ISSUE TITLE
Negative coordinates presented with spurious negative signs in Geo-localized points window

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#76]
**Describe the bug**
When presenting negative coordinates (west longitudes and south latitudes) in dd°mm'ss.ss" format the _Geo-localized_ points window adds negative signs not only to the degrees but also to minutes and seconds like this:
-45°-23'-12.55
when it should present it as:
-45°23'12.55
for longitude W 45:23:12.55

It also rounds wrongly negative coordinates presenting:
-15°03'56.41
as
-15°03'56.40
for latitude S 15:3:56.41

At last it doesn´t includes the seconds sign presenting
-15°03'56.41
when it should present
-15°03'56.41"

**To Reproduce**
1. Go to _Geo-localized_ points window and manuall add the above coordinates examples
2. Look at the _Geo-localized_ points window  how these coordinates are presented and see the issues mentioned above.

**Device (please complete the following information):**
 - TopoDroid version: 6.2.12-33

**Comment by rsevero** [comment]
Fixed by commit [de20caa6e](https://github.com/marcocorvi/topodroid/commit/de20caa6e1e35dc4ce3d96a5a8548c4a927bd25a)

**Comment by marcocorvi** [comment]
thanks
