### ISSUE TITLE
"Line join" button does not reappear after choosing back "wall" line type

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#81]
**Describe the bug**
After starting to draw with "wall" line type and have the "line join" option available, choosing another line type like "user" makes the "line join" button disapppear and getting back to "wall" does not make the "line join" button reappear.

**To Reproduce**
1. Start to draw with line type "wall"
2. See that the " line join" button is available
3. Choose line type "usar"
4. See that "line join" button disappeared
5. Choose line type "wall"

**Expected behavior**
"Line join" button should reappear but it does not. To get it back I need to leave the drawing window and come back

**Device (please complete the following information):**
- Samsung Galaxy S21 FE and Motorola A32
- Android version 13
- TopoDroid version 6.2.34-33

**Comment by marcocorvi** [comment]
revised the code.
hopefully fixed in the next version
