### ISSUE TITLE
"Config > Custom settings > Sketching > Legs-only refresh" option not working

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#84]
**Describe the bug**
No matter how I set "Config > Custom settings > Sketching > Legs-only refresh"  option, the drawing is only refreshed when a new leg is received. It would be great to have the "refresh on all new data" option working.

**To Reproduce**
1. Turn on "Config > Custom settings > Sketching > Legs-only refresh"
2. Receive new splays and see that the drawing isn't refreshed
3. Turn off "Config > Custom settings > Sketching > Legs-only refresh"
4. See that the behaviour is the same, i.e., receiving new splays does not refresh the drawing

**Expected behavior**
With  "Config > Custom settings > Sketching > Legs-only refresh" off the drawing should be refreshed on all data received, even only splays.

**Comment by rsevero** [comment]
My bad. It is working.

**Comment by rsevero** [comment]
Unfortunatelly this is another issue that is erratic. Tested it yesterday, before going to the cave. It was ok. Inside the cave started to have this issue again.

I am trying to identify what events makes this behaviour to start. I already know that closing TopoDroidX AND forcing it to stop in Android makes it stop.

**Comment by rsevero** [comment]
[teste2.zip](https://github.com/marcocorvi/topodroid/files/13840334/teste2.zip)

With this file with TopodroidX 6.2.35 and a BRIC4 I have 2 issues:

1. setting active station still ignored, i.e., new splays created from last created station, ignmoring "active station" setting
2. turning off "legs-only refresh" inefective: to see new splays I have to go to shots list and them back to drawing window.

**Comment by marcocorvi** [comment]
Only with bric4 or also with distox2 ?

**Comment by rsevero** [comment]
> Only with bric4 or also with distox2 ?

The tests that failed were with a BRIC4 for sure but the distos that where around in the expedition just left so I can't be sure if it is restricted to the BRIC or not.

**Comment by marcocorvi** [comment]
there was an error:
the setting did not apply at tester level - while it should apply only at tester level :-)

in order to check with 6.2.35 try level expert.

**Comment by rsevero** [comment]
It worked on level expert. When I came back to tester it kept working.

**Comment by marcocorvi** [comment]
possibly fixed in v. 6.2.36

the leg-only refresh is a tester-level setting and it should be ignored at lower levels.

**Comment by marcocorvi** [comment]
it could not be reproduced.
closed by lack of further feedbacks
