### ISSUE TITLE
When importing zip files with survey names already present a confusing error message is presented: "invalid manifest file"

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#93]
**Describe the bug**
When importing zip files with survey names already present a confusing error message is presented: "invalid manifest file"

**To Reproduce**
1. Try to import a zip file with a survey already present in Topodroid
2. see that the error message does not explain what is happening. Instead it says "invalid manifest file"

**Expected behavior**
Present an informative error message like "Duplicated survey name". It would be great if it also offered the option to import the survey with a new name.

**Device (please complete the following information):**
 - Samsung 21FE
 - Android 13
 - TopoDroid 6.2.51

**Comment by marcocorvi** [comment]
fixed by v. 6.2.55
