### ISSUE TITLE
"Refresh" button separated by empty space from the other buttons at "draw section" window

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#96]
**Describe the bug**
"Refresh" button separated by empty space from the other buttons at "draw section" window

**To Reproduce**
1. Set "test" resource level
2. Go to "draw section" window
3. See that there is an empty space between the "refresh" button and the other buttons.

**Expected behavior**
The "refresh" button should have no empty space separating it from the other buttons.

**Screenshots**
![Screenshot_20240401_132854_TopoDroid-X](https://github.com/marcocorvi/topodroid/assets/315152/74488d83-4fd8-4954-949e-ce95fcd12e17)

**Device (please complete the following information):**
 - Samsung Galaxy 23 FE
 - Android 14
 - TopoDroid 6.2.57-34

**Comment by marcocorvi** [comment]
removed refresh button from the interface.
it is not very important for x-section

**Comment by rsevero** [comment]
> removed refresh button from the interface. it is not very important for x-section

Really!?

I use it a lot as new plays never appear automatically on X-sections.

**Comment by marcocorvi** [comment]
no need to reopen: you should have checked the sources.
there is a set of buttons specific for x-sections, now.
