### ISSUE TITLE
Renaming station of shot where the other station  has a section results in "Station used in section" warning message

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#97]
**Describe the bug**
Renaming station of shot where the other station  has a section results in "Station used in section" warning message

**To Reproduce**
1. Set "test" resource level
2. Create a section on a station using the "compass" button
3. Create a shot from this same station
4. Try to rename the newly created station
5. See that a "station used in section" message appears

**Expected behavior**
Renaming a station not used in a section should not trigger the "station used in section" message even if it's connected to a station with a section.

**Device (please complete the following information):**
- Samsung Galaxy 23 FE
- Android 14
- TopoDroid 6.2.57-34

**Comment by marcocorvi** [comment]
maybe
