### ISSUE TITLE
Make exported Therion files self compatible

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#98]
**Describe the bug**
Make exported Therion files self compatible

**To Reproduce**
1. Export a survey in Therion format with a thconfig file
2. Open the generated thconfig file in xtherion
3. Try to compile
4. See xTherion complaing that it can't find the "th" file as it's looking for the "th" file in a non existent "../th" directoy

**Expected behavior**
xTherion should be able to compile the generated files from Topodroid so the generated thconfig file should look for the "th" file on the same directoy as the thconfig file

**Device (please complete the following information):**
- Samsung Galaxy 23 FE
- Android 14
- TopoDroid 6.2.57-34

**Comment by marcocorvi** [comment]
fixed
